### PR TITLE
add lastUpdated field to route /user/projects

### PR DESCRIPTION
**Pull request by monperrus**
### Description

Add lastUpdated field to route /user/projects. This is required to make a resource aware incremental backup. Will reduce the load on overleaf's servers.

#### Manual Testing Performed

- [ ]
- [ ]

#### Deployment Checklist

- [ ] Update documentation not included in the PR (if any)
- [ ]

### CODE REVIEW

**Comment by monperrus** [comment]
ping @lawshe

**Comment by gh2k** [comment]
Thank you for taking the time to submit this.

We generally prefer to keep data out of the rendered pages unless it is going to be used by something in the UI, and it looks like the reason why you're looking for this is for some kind of external script, which isn't something we officially support right now, so I'm going to close this for now.

I've made a note of your use case and this might be something we can look into again in the future.

**Comment by monperrus** [comment]
Thanks a lot @gh2k for your answer

I don't find this information anywhere in the doc. 

Can we get this information on a project specific end-point? 

Something like

```
/project/<projectid>/XXXX

{
  "id" :  "<projectid>",
  "lastUpdated" : "2020-12-12"
  ...
}
```

WDYT?

Thanks! --Martin

**Comment by gh2k** [comment]
Thanks for this idea. We do have conversations internally about what we might provide as part of an API, and this is definitely a use case for that.

Unfortunately, we're still not going to add something to the main app to support an external use case without considering it as part of a larger piece of work on making a documented API. Otherwise, what we end up with is a bunch of undocumented things that we then have to maintain for external users.

It *is* a good idea, but not something that we are going to implement for now. Sorry about that.

**Comment by monperrus** [comment]
OK thanks Simon. --Martin

**Pull request closed without merging**
