### PR TITLE
[misc] Add a copy the the GNU Affero General Public License v3.0

### PR DESCRIPTION
**Pull request by das7pad**
RE https://github.com/overleaf/notifications/pull/9

### CODE REVIEW

**Comment by robertacucuzza** [comment]
Questions...
Is there an impact to the user? 
What is the benefit?

**Comment by das7pad** [comment]
The license notice is currently more or less hidden in the readme.

> Is there an impact to the user?

I am unsure what kind of impact you are referring to.

> What is the benefit?

Github can parse the license file and display it - see one of the other projects or your org view on github.


Additionally let me quote from the GNU web page [0]:

> You should also include a copy of the license itself somewhere in the distribution of your program.


---
[0] https://www.gnu.org/licenses/gpl-howto.en.html

**Comment by 40thieves** [comment]
@das7pad Just fyi I think the question was an oversight from our PM who didn't realise this was an OSS issue :) I'll see if we can get this merged

**Comment by das7pad** [comment]
cc @40thieves @jdleesmiller shall we import this PR?

**Comment by jdleesmiller** [comment]
👍 yes please

**Comment by das7pad** [comment]
Imported in https://github.com/overleaf/web/commit/15017afc1cb085412658031f3bcd6ab88769a19b

**Pull request closed without merging**
